[font]
size = 11.0

[font.bold]
family = "Source Code Pro"

[font.italic]
family = "Source Code Pro"

[font.normal]
family = "Source Code Pro"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
opacity = 1.0

[general]
live_config_reload = true
import = ["/home/italo/.config/alacritty/colors.toml"]
