# https://wiki.hyprland.org/Configuring/Binds/#submaps
bind = $mainMod, R, submap, resize

submap=resize

binde = , l, resizeactive, 20 0
binde = , h, resizeactive, -20 0
binde = , k, resizeactive, 0 -20
binde = , j, resizeactive, 0 20

bind= , escape, submap, reset
bind= $mainMod, R, submap, reset

submap=reset
