windowrule {
  name = opacity
  border_color = $base0F $base03
  opacity = 0.90
  match:float = 1
  match:fullscreen = 0
}

windowrule {
  name = float-volume-control
  float = on
  match:title = ^Volume Control$
}

windowrule {
  name = float-bluetooth
  float = on
  match:title = ^Bluetooth Devices$
}

windowrule {
  name = float-firefox-pip
  float = on
  match:class = ^firefox$
  match:title = ^Picture-in-Picture$
}
