[[item]]
file = "~/.config/alacritty/colors.yml"
template = "alacritty"
rewrite=true

[[item]]
file = "~/.config/sway/colors"
template = "sway"
subtemplate = "colors"
light = false
hook = "swaymsg reload"
rewrite=true

[[item]]
file = "~/.config/waybar/colors.css"
template = "waybar"
hook = "pkill -SIGRTMIN+7 waybar"
rewrite = true

[[item]]
file= "~/.tmux/theme.conf"
template = "tmux"
subtemplate = "custom"
hook = "tmux source-file ~/.tmux.conf"
rewrite = true
